[package]
name = "archivoor-v1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
headless_chrome = "0.9.0"
reqwest = "0.11.13"
signal-hook = "0.3.14"
