collections_root: collections
archive_paths: archive
index_paths: indexes
static_path: static
templates_dir: templates

framed_replay: false
debug: true

autoindex: 3

recorder:
  dedup_policy: skip
  dedup_index_url: "redis://localhost:6379/0/pywb:{coll}:cdxj"
  source_coll: live
  filename_template: archivoor-{timestamp}-{hostname}-{random}.warc.gz
