collections_root: collections
archive_paths: archive
index_paths: indexes
static_path: static
templates_dir: templates

framed_replay: false

recorder:
  source_coll: live
  filename_template: archivoor-{timestamp}.warc.gz
