version: "3.9" 
services:
  crawler:
    build: .
    depends_on:
      - redis
    command: tail -f /dev/null
    network_mode: host
    extra_hosts:
        - "host.docker.internal:host-gateway"
  redis:
    image: redis
